### ISSUE TITLE
Странный эффект на кнопке добавления ставк

### ISSUE THREAD

**Issue by dshemin** [htmlacademy-php/1021437-yeticave-12#20]
**Steps to reproduce:**
- Открыть страницу лота будучи аутентифицированным
- Нажать на кнопку "Сделать"

**Actual result:**
<img width="362" alt="Снимок экрана 2020-05-09 в 20 32 54" src="https://user-images.githubusercontent.com/11780307/81475161-9f7dd500-9234-11ea-9502-1e072d669f6d.png">

**Expected result:**

**Comment by moiseenkob** [comment]
Fixes #26
